example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from mywatchlist.views import show_json, show_mywatchlist, show_xml

app_name = 'mywatchlist'

urlpatterns = [
    
    path('html/',show_mywatchlist , name='show_mywatchlist'),
    path('xml/',show_xml , name='show_xml'),
    path('json/',show_json , name='show_json'),


]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/',include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),

]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import change_task_status, delete_task, register,login_user,logout_user,show_todolist,create_task,show_json,add_task

app_name = 'todolist'

urlpatterns = [
    
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('',show_todolist,name='show_todolist'),
    path('create-task/',create_task,name='create-task'),
    path("change-task-status/<int:pk>/", change_task_status, name = "change-task-status"),
    path("delete-task/<int:pk>/", delete_task, name = "delete-task"),
    path('json/',show_json,name="show_json"),
    path('add/',add_task,name="add_task")


]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchlistItem(models.Model):
    watched= models.TextField(max_length=255)
    title = models.TextField()
    rating = models.FloatField()
    release_date = models.TextField()
    review = models.TextField()
    

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)
    

todolist/forms.py
from django import forms
from todolist.models import Task
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description')
        
    

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render 

from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_catalog_items = CatalogItem.objects.all()
    context = {
        'catalog_items': data_catalog_items,
        'nama': 'Yoozu'
    }
    return render(request, "katalog.html",context)

mywatchlist/views.py
from http.client import HTTPResponse
from django.shortcuts import render 
from django.http import HttpResponse
from django.core import serializers

from mywatchlist.models import MyWatchlistItem

# TODO: Create your views here.
data_mywatchlist_items = MyWatchlistItem.objects.all()
def show_mywatchlist(request):
    
    context = {
        'watchlist_items': data_mywatchlist_items,
        'nama': 'Yoozu',
        'NPM': '2106751064'
    }
    return render(request, "mywatchlist.html",context)
def show_xml(request):
    
    return HttpResponse(serializers.serialize("xml", data_mywatchlist_items), content_type="application/xml")

def show_json(request):
    
    return HttpResponse(serializers.serialize("json", data_mywatchlist_items), content_type="application/json")

todolist/views.py
import json
from django.urls import reverse
from http.client import HTTPResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from .models import Task
from .forms import TaskForm
from django.http import HttpResponseRedirect, HttpResponse


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
            
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response 
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    tasks = Task.objects.filter(user = request.user)
    context = {'Nama':'Yoozu Abiyyu Verisson',
                'tasks':tasks,
                'Student_ID':'2106751064',
                'user:':request.user}

    return render(request, "todolist.html",context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    if(request.method == "POST"):
        form = TaskForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
           
        return redirect('todolist:show_todolist')
    context = {}
    return render(request, 'create.html', context)

@login_required(login_url='/todolist/login/')
def change_task_status(request, pk):
    if(Task.objects.get(pk = pk).is_finished == True and Task.objects.get(pk=pk).user == request.user):
        Task.objects.filter(pk = pk).update(is_finished = False)
    else:
        if(Task.objects.get(pk=pk).user == request.user):
            Task.objects.filter(pk = pk).update(is_finished = True)
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def delete_task(request, pk):
    if(Task.objects.get(pk=pk).user == request.user):
        Task.objects.filter(pk = pk).delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def show_json(request):
   
    data = Task.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def add_task(request):
    if(request.method == "POST"):
        form = TaskForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
           
        return HttpResponse()
    return HttpResponse()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h3>Name: {{nama}} </h5>
  <p></p>

  <h3 >Student ID: 2106751064 </h5>
  <p></p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
{% for item in catalog_items %}
    <tr>
        <th>{{item.item_name}}</th>
        <th>{{item.item_price}}</th>
        <th>{{item.item_stock}}</th>
        <th>{{item.description}}</th>
        <th>{{item.rating}}</th>
        <th><a href="{{item.item_url}}">{{item.item_url}}</a></th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

{% block content %}
<h1>Assignment 3 PBP/PBD</h1>

  <h3>Name: {{nama}} </h5>
  <p></p>

  <h3 >Student ID: {{NPM}} </h5>
<table>
    <tr>
    <th>Watched</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Release date</th>
    <th>Review</th>
    </tr>
    {% for data in watchlist_items %}
    <tr>
      <th>{{data.watched}}</th>
      <th>{{data.title}}</th>
      <th>{{data.rating}}</th>
      <th>{{data.release_date}}</th>
      <th>{{data.review}}</th>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>
<style>
  table,
  th,
  td {
    border: 1px solid black;
  }
</style>
<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/create.html
{% extends 'base.html' %}

{% block meta %}
<title> Create Task </title>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
<div>

    <h1 class = "display-5 mb-4 pt-3" style="text-align: center;">Create Task</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table class="table table-success table-striped">
             
            <tr>
                <td>Title: </td>
                <td><input type="text" name="title" id="title" placeholder="Title" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td><input type="description" name="description" id="description" placeholder="Description" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn btn-success" type="submit" value="Submit"></td>
            </tr>
        </table>
    </form>
     
</div>
</div>
<script>
</script>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
<div class = "login">

    <h1 class = "display-5 mb-4 pt-3" style="text-align: center;">Login</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <table class="table table-success table-striped">
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn btn-primary"type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  


<div class="container-fluid">
    <h1 class = "display-5 mb-4 pt-3" style="text-align: center;">Formulir Registrasi</h1>

        <form method="POST" >  
            {% csrf_token %}  
            <table class="table table-striped">
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input class="btn btn-primary" type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  
</div>    

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}


{% block content %}

<script>window.CSRF_TOKEN = "{{csrf_token}}"</script>

<h1 class="text-center" style="font-family: Fanstasy;">To Do List</h1>
<div class="fst-italic">
  <h5>Name: {{Nama}}</h5>
  <p> </p>

  <h5>Student ID: {{Student_ID}} </h5>
  <p> </p>

  <h5> User sekarang: {{user}} </h5>
  <p> </p>
</div>


{% comment %} Add the data below this line {% endcomment %}

<div id="list"></div>

<script>
  let myModal

  function reloadList() {
    $.get("{% url 'todolist:show_json' %}", function (data) {
      $('#list').empty()
      $.each(data, function (index, value) {
        let kartuYangMauDitambah = `    <div class="card mb-3" style="width: 30%; margin:auto">
      
      <div class="card-body">
        <h4>${value.fields.title}</h4>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>User:  </strong>  ${value.fields.user}</li>
          <li class="list-group-item"><strong>Date:  </strong>${value.fields.date}</li>
          <li class="list-group-item mb-2"><strong>Description: </strong>  ${value.fields.description}</li>
        </ul>`

        if (value.fields.is_finished) {
          kartuYangMauDitambah += `<p style="color:blue;">Selesai</p>`
        } else {
          kartuYangMauDitambah += `<p style="color:red;">Belum Selesai</p>`
        }

        kartuYangMauDitambah += `<div style="text-align: center;">
        <th> <button class="btn btn-secondary" id="gantistatus-${value.pk}" style="color: white;"> Ganti Status Pekerjaan</button> </th>
        <th> <button class="btn btn-warning" id="hapus-${value.pk}"><a href""> Hapus Data </a></button> </th>
    </div>
      </div>
    
  </div>`
        $('#list').append(kartuYangMauDitambah)

        $(`#gantistatus-${value.pk}`).click(() => $.ajax(`change-task-status/${value.pk}/`, {
          success: () => reloadList()
        })
        )
        $(`#hapus-${value.pk}`).click(() => $.ajax(`delete-task/${value.pk}/`, {
          success: () => reloadList()
        })
        )

      })
    })

  }

  $(document).ready(function () {
    myModal = new bootstrap.Modal('#exampleModal', {
      keyboard: false
    })

    $('#ajax').submit(event => {
      event.preventDefault()
      $.ajax({
        url: "add/", // the endpoint
        method: "POST", // http method
        data: {
          title: $('#title').val(),
          description: $('#description').val()
        },
        headers: {
          "X-CSRFToken": window.CSRF_TOKEN
        },

        success: function (json) {
          myModal.hide()
          reloadList()
        },

        error: function (xhr, errmsg, err) {
          // $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: " + errmsg +
          //   " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
          console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
      });

    })
  })

  reloadList()


</script>


<div class="mb-4" style="text-align: center;">
  <button class="btn btn-primary" style="color: white;" data-bs-toggle="modal" data-bs-target="#exampleModal"> Create
    Task
  </button>

  <a class="btn btn-danger" style="color: white;" href="{% url 'todolist:logout' %}">Logout</a>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h1 class="display-5 mb-4 pt-3" style="text-align: center;">Create Task</h1>

        <form id="ajax" method="POST" action="create-task/">
          {% csrf_token %}
          <table class="table table-success table-striped">

            <tr>
              <td>Title: </td>
              <td><input id="title" type="text" name="title" placeholder="Title" class="form-control"></td>
            </tr>

            <tr>
              <td>Description: </td>
              <td><input id="description" type="description" name="description" placeholder="Description"
                  class="form-control"></td>
            </tr>

            <tr>
              <td></td>
              <td><input class="btn btn-success" type="submit" value="Submit"></td>
            </tr>
          </table>
        </form>

      </div>
    </div>
  </div>
</div>


{% endblock content %}